# Generated by Django 3.2.25 on 2025-09-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_red_score', models.IntegerField(default=0)),
                ('team_blue_score', models.IntegerField(default=0)),
                ('round_number', models.IntegerField(default=1)),
                ('game_time', models.IntegerField(default=180)),
                ('game_running', models.BooleanField(default=False)),
                ('penalty_time', models.IntegerField(default=0)),
                ('penalty_running', models.BooleanField(default=False)),
                ('team_red_name', models.CharField(default='Red Team', max_length=50)),
                ('team_blue_name', models.CharField(default='Blue Team', max_length=50)),
            ],
        ),
    ]
